version: '3.8'

services:
  flask_app:
    container_name: flask-app
    build:
      context: ./app
    ports:
      - "5000:5000"
    networks:
      - app_net
    environment:
      OPENAI_API_KEY: 
    volumes:
      - ./app:/app

networks:
  app_net:
    driver: bridge
